/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ink: 'rgb(var(--ink-rgb) / <alpha-value>)',
        accent: 'rgb(var(--accent-rgb) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover-rgb) / <alpha-value>)',
        'accent-alt': 'rgb(var(--accent-alt-rgb) / <alpha-value>)',
        'accent-soft': 'rgb(var(--accent-soft-rgb) / <alpha-value>)',
        info: 'rgb(var(--info-rgb) / <alpha-value>)',
        'info-hover': 'rgb(var(--info-hover-rgb) / <alpha-value>)',
        'info-soft': 'rgb(var(--info-soft-rgb) / <alpha-value>)',
        surface: 'rgb(var(--surface-rgb) / <alpha-value>)',
        paper: 'rgb(var(--paper-rgb) / <alpha-value>)',
        'paper-2': 'rgb(var(--paper-2-rgb) / <alpha-value>)',
        strong: 'rgb(var(--text-strong-rgb) / <alpha-value>)',
        secondary: 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
        success: 'rgb(var(--success-rgb) / <alpha-value>)',
        'success-soft': 'rgb(var(--success-soft-rgb) / <alpha-value>)',
        'success-tint': 'rgb(var(--success-tint-rgb) / <alpha-value>)',
        warning: 'rgb(var(--warning-rgb) / <alpha-value>)',
        gold: 'rgb(var(--gold-rgb) / <alpha-value>)',
        cream: 'rgb(var(--cream-rgb) / <alpha-value>)',
        peach: 'rgb(var(--peach-rgb) / <alpha-value>)',
      },
      boxShadow: {
        'brutal-sm': '2px 2px 0px var(--shadow-color)',
        brutal: '3px 3px 0px var(--shadow-color)',
        'brutal-md': '4px 4px 0px var(--shadow-color)',
        'brutal-5': '5px 5px 0px var(--shadow-color)',
        'brutal-lg': '6px 6px 0px var(--shadow-color)',
        'brutal-xl': '8px 8px 0px var(--shadow-color)',
        'brutal-2xl': '12px 12px 0px var(--shadow-color)',
        'brutal-accent': '4px 4px 0px var(--accent)',
        'brutal-gold': '6px 6px 0px var(--gold)',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'serif': ['IBM Plex Serif', 'Playfair Display', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};
