/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ink: 'var(--ink)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-alt': 'var(--accent-alt)',
        'accent-soft': 'var(--accent-soft)',
        info: 'var(--info)',
        'info-hover': 'var(--info-hover)',
        'info-soft': 'var(--info-soft)',
        surface: 'var(--surface)',
        paper: 'var(--paper)',
        'paper-2': 'var(--paper-2)',
        strong: 'var(--text-strong)',
        secondary: 'var(--text-secondary)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        'success-tint': 'var(--success-tint)',
        warning: 'var(--warning)',
        gold: 'var(--gold)',
        cream: 'var(--cream)',
        peach: 'var(--peach)',
      },
      boxShadow: {
        'brutal-sm': '2px 2px 0px var(--shadow-color)',
        brutal: '3px 3px 0px var(--shadow-color)',
        'brutal-md': '4px 4px 0px var(--shadow-color)',
        'brutal-5': '5px 5px 0px var(--shadow-color)',
        'brutal-lg': '6px 6px 0px var(--shadow-color)',
        'brutal-xl': '8px 8px 0px var(--shadow-color)',
        'brutal-2xl': '12px 12px 0px var(--shadow-color)',
        'brutal-accent': '4px 4px 0px var(--accent)',
        'brutal-gold': '6px 6px 0px var(--gold)',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'serif': ['IBM Plex Serif', 'Playfair Display', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};
